services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qlhssv_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1401:1433"
    volumes:
      - qlhssv_db_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  qlhssv_db_data:
    external: true